---
# Adds  extra CA Certificates
- name: Install ca-certificates package
  package:
    name: ca-certificates
    state: present

- name: Ensure certificates directory exists
  file:
    path: "{{ ca_path }}/"
    state: directory

- name: Install CA Certificates
  copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    owner: root
    group: root
    mode: "0644"
  with_fileglob:
    - ca/*
  notify:
    - Update trusted CA certificates

- name: Ensure RSysLog Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Configure RSysLog
  template:
    src: "etc/rsyslog.d/remote_logs.conf.j2"
    dest: "/etc/rsyslog.d/00_{{ remote_logs_server }}.conf"
  notify:
    - Restart RSysLog
